name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
        
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build
        run: cargo check --all
        
      - name: Format check
        run: cargo fmt --all -- --check
  
      - name: Clippy
        uses: giraffate/clippy-action@v1
        with:
          clippy_flags: --all --lib --bins --examples
          filter_mode: nofilter
          reproter: 'github-pr-review'
      
      - name: Test
        run: cargo test --all
